name: ci

on:
  - push

permissions:
  id-token: write
  contents: read

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: Setup PNPM
        uses: pnpm/action-setup@v6
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Check code quality
        run: pnpm lint
      - name: Build packages
        run: pnpm build
      - name: Publish packages
        if: github.ref_name == 'main'
        run: pnpm publish
